### ISSUE TITLE
Black Screen on Startup

### ISSUE THREAD

**Issue by Flohkiste** [JonnyOThan/Kerbal-VR#252] opened 2023-02-08 17:04 UTC
**Describe the bug**
I don´t even get to the Main Menu. The screen is just black in vr and on my monitor.

**To Reproduce**

**Expected behavior**
Getting into the Main Menu screen

**Log**
Attach a copy of the KSP.log file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - KSP Version: 1.12.5
 - VR Hardware: Oculus Quest 2 
 - Kerbal-VR Version:  0.9.0.2
**Additional context**
[KSP.log](https://github.com/JonnyOThan/Kerbal-VR/files/10688094/KSP.log)

**Comment by JonnyOThan** [comment] 2023-02-10 03:19
Seems like this is the relevant failure, but I have no idea what might cause it.  Maybe need to restart SteamVR.

```
[EXC 17:58:37.066] NullReferenceException: Object reference not set to an instance of an object
	Valve.VR.SteamVR_Action_Pose.SetTrackingUniverseOrigin (Valve.VR.ETrackingUniverseOrigin newOrigin) (at <df405e33c14345feac2340b0178ceb35>:0)
	Valve.VR.SteamVR_Input.Initialize (System.Boolean force) (at <df405e33c14345feac2340b0178ceb35>:0)
	KerbalVR.Core.InitSteamVRInput () (at <4c646565488042c68d585ce91109346e>:0)
	KerbalVR.FirstPersonKerbalAddon.Awake () (at <4c646565488042c68d585ce91109346e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	<LoadObjects>d__90:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CreateDatabase>d__71:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	GameDatabase:StartLoad()
	<LoadSystems>d__11:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	LoadingScreen:Start()
```

**Comment by JonnyOThan** [comment] 2023-02-10 03:21
oop, seems like a dupe of #234

**Closed by JonnyOThan** 2023-02-10 03:21 UTC
