### ISSUE TITLE
Cockpit appears too tiny to allow enough space to press buttons etc. on WMR (Reverb G2). I think world scale is wrong.

### ISSUE THREAD

**Issue by romandesign** [JonnyOThan/Kerbal-VR#238] opened 2023-01-26 16:29 UTC
**Describe the bug**
The cockpit appears too tiny to allow enough space to press buttons etc. on WMR (Reverb G2). I think world scale is wrong. The panels appear to be located right in front of your face, so the controllers are either too close to HMD to track properly, frequently bumping into HMD when trying to do anything, losing tracking, or if I move a hand a bit forward to track and point properly - the hand is already clipping and is buried inside the panel - this is all on Mk1 cockpit. The problem seems to be the world scale - however manually increasing the world scale in Steam VR make hands appear huge. I modified the hand size in config as a temporary fix. I think the scale is now set to 125% in SteamVR and hand scale is set to scale = 0.5 in config. This makes it tolerable. I understand that Kerbals are smaller than humans, so maybe the scale is correct, but it doesn't feel correct at all, and doesn't allow to operate controls properly. Maybe the scale should be adjusted individually for different IVAs, depending on internal size? Some may be OK - didn't make it past Mk1 yet.

**To Reproduce**
Load Mk1 cockpit, go to VR in WMR HMD.

**Expected behavior**
Enough room for hands to move, be tracked and operate controls, not bump to HMD or clip inside panels

**Desktop (please complete the following information):**
 - Windows 11
 - KSP Version: 1.12.5.3190
 - VR Hardware: Reverb G2
 - Kerbal-VR Version: 0.9.0

**Comment by JonnyOThan** [comment] 2023-01-27 15:01
Dupe of #228

**Closed by JonnyOThan** 2023-01-27 15:01 UTC
